QUESTIONS: 1b 3 5a 5b 6a 6b 6c 10 11a 11b 11c 12

all: $(QUESTIONS)

1b: 1b.c
	cc 1b.c -Wall -o 1b

3: 3.c
	cc 3.c -Wall -o 3

5a: 5a.c
	cc 5a.c -Wall -o 5a

5b: 5b.c
	cc 5b.c -Wall -o 5b
6a: 6a.c
	cc 6a.c -Wall -o 6a
6b: 6b.c
	cc 6b.c -Wall -o 6b
6c: 6c.c
	cc 6c.c -Wall -o 6c
10: 10.c
	cc 10.c -Wall -o 10
11a: 11a.c
	cc 11a.c -Wall -o 11a
11b: 11b.c
	cc 11b.c -Wall -o 11b
11c: 11c.c
	cc 11c.c -Wall -o 11c
12: 12.c
	cc 12.c -Wall -o 12c

.PHONY: clean

clean:
	rm -f 1b 3 5a 5b 6a 6b 6c 10 11a 11b 11c